config/locales/affordability.cy.yml, config/locales/mortgage_calculator.cy.yml, config/locales/stamp_duty.cy.yml
Relates to:
* https://trello.com/c/Hy7Sw2hS
* https://trello.com/c/ixBgBst8
* https://trello.com/c/cdVLrpyC
=> Update title and meta descriptions with Welsh translations

config/routes.rb, spec/controllers/affordabilities_controller_spec.rb
As it is no longer needed
cc @munckymagik This should fix the build
=> remove affordability calculator feature toggle

package.json
This fixes the
https://go.test.moneyadviceservice.org.uk/go/tab/build/detail/mortgage_calculator/627/test/1/test
=> Update versions of karma-jasmine and phantomjs

app/assets/stylesheets/mortgage_calculator/layouts/_sticky.scss
- reduces depth of element
Integrates with PR1365 on frontend
=> id: 6920, comment: updates sticky element for better mobile experience

app/views/mortgage_calculator/stamp_duties/_bands_table.html.erb, config/locales/stamp_duty.cy.yml, config/locales/stamp_duty.en.yml
7046 - Stamp Duty Calculator - Post April - 2nd home text fix
Added paragraph highlighted in red:
| English | Welsh |
|------------|---------|
|<img width="597" alt="screen shot 2016-02-16 at 08 43 35" src="https://cloud.githubusercontent.com/assets/13165846/13071169/a1162cfe-d489-11e5-94a0-0e115b8507a0.png">|<img width="600" alt="screen shot 2016-02-16 at 08 44 28" src="https://cloud.githubusercontent.com/assets/13165846/13071171/a55148d0-d489-11e5-98c1-d35946f825e8.png">|
=> [DEV APPROVED] #7046 - Updating text for additional home

app/models/mortgage_calculator/affordability.rb, features/affordability.feature, features/step_definitions/affordability.rb, features/support/javascript.rb, spec/models/affordability_spec.rb, spec/models/interest_only_spec.rb, spec/models/outgoings_spec.rb, spec/models/person_spec.rb, spec/models/repayment_spec.rb
This PR contains changes addressing comments from @tomas-stefano and myself on [an earlier PR](https://github.com/moneyadviceservice/mortgage_calculator/pull/250), after the original author @oneKelvinSmith was pulled away onto other tasks..
=> 7427 - changes addressing comments on the "affordability calculator enhancements" PR

lib/mortgage_calculator/version.rb
In my previous PR I forgot to increment the version number of this tool in accordance with semantic versioning. This PR does just that.
=> Version bump for 7350 (slider bug)

app/assets/stylesheets/mortgage_calculator/components/_stamp-duty-calc.scss, app/views/mortgage_calculator/stamp_duties/_stamp_duty_tip.html.erb
=> Reducing vertical space

config/locales/mortgage_calculator.cy.yml, config/locales/mortgage_calulator.en.yml, lib/mortgage_calculator/version.rb
Updates to English and Welsh text and links on the final step of the mortgage calculator.
| English | Welsh |
|---------|-------|
|<img width="616" alt="screen shot 2016-12-13 at 14 41 11" src="https://cloud.githubusercontent.com/assets/13165846/21144430/771fcdaa-c142-11e6-8237-fbda25e4ac1c.png">|<img width="646" alt="screen shot 2016-12-13 at 14 40 24" src="https://cloud.githubusercontent.com/assets/13165846/21144437/7d396ed0-c142-11e6-973b-25cafe9ff9d7.png">|
=> [DEV APPROVED] 7845 - Change Mortgage Calculator Next Step links

app/assets/stylesheets/mortgage_calculator/components/_featured-list.scss, app/assets/stylesheets/mortgage_calculator/components/_mortgagecalc.scss, app/assets/stylesheets/mortgage_calculator/components/_tabs.scss, app/assets/stylesheets/mortgage_calculator/lib/_variables.scss, app/views/mortgage_calculator/affordabilities/_next_steps_content.html.erb, app/views/mortgage_calculator/repayments/_calc_left_panel.html.erb, app/views/mortgage_calculator/repayments/_calc_right_panel.html.erb, app/views/mortgage_calculator/repayments/_next_steps_content.html.erb, app/views/mortgage_calculator/repayments/_suggested_tools.html.erb, app/views/mortgage_calculator/repayments/_tabs.html.erb, app/views/mortgage_calculator/repayments/next_steps.html.erb, app/views/mortgage_calculator/repayments/show.html.erb, app/views/mortgage_calculator/stamp_duties/_form_step2.html.erb, features/analytics.feature, features/step_definitions/repayment.rb, spec/controllers/repayments_controller_spec.rb
- Removed last step of the process
- Updated callout boxes markup and positioning
- Moved next steps into 2nd step
- Added recommended tools to 2nd step and placed into partial
Please see the [ticket here](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx?acid=E9844BE5A953DC8AF06B0B23D5B7DBA0#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&boardPopup=userstory/8022/silent) for the layout requirements
| Desktop | Mobile |
|---------|--------|
|<img src="https://cloud.githubusercontent.com/assets/13165846/23702211/38f8acfc-03f2-11e7-8636-e352d9ffbda3.png" width="400" />|<img src="https://cloud.githubusercontent.com/assets/13165846/23702343/bfb48c5c-03f2-11e7-8308-34c37a7cc40d.png" width="250" />|
=> [DEV APPROVED] 8022 ab result change

app/views/mortgage_calculator/repayments/_next_steps_content.html.erb, config/locales/mortgage_calculator.cy.yml, config/locales/mortgage_calulator.en.yml, lib/mortgage_calculator/version.rb
| English | Welsh |
|--------|--------|
|![image](https://cloud.githubusercontent.com/assets/13165846/23949325/c006041a-097e-11e7-9a11-8d3070885e33.png)|![image](https://cloud.githubusercontent.com/assets/13165846/23949261/8c46ba20-097e-11e7-9769-d98b6897208d.png)|
=> 8022 updating copy

build.sh, lib/mortgage_calculator/version.rb
Adding bowndler to build script to fetch the latest version of yeast for ticket 8150, new yellow!
=> 8150 - Adding bowndler to build script

app/assets/javascripts/mortgage_calculator/angular/services/stamp_duty.js, app/assets/stylesheets/mortgage_calculator/components/_stamp-duty-calc.scss, app/views/mortgage_calculator/stamp_duties/_stamp_duty_to_pay_panel.html.erb, config/locales/stamp_duty.cy.yml, config/locales/stamp_duty.en.yml, spec/javascripts/unit/services/stampDuty.js
[TP8710](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=userstory/8706&appConfig=eyJhY2lkIjoiREREN0YzQTYyNjg0NEFCOEQxQkVFM0YwNkVDMjhFRkEifQ==&searchPopup=userstory/8710)
This PR adds a conditional message in the results section for First Time Buyers only when the property price is greater than £500k.
=> TP: 8710, Comment: Adds conditional message for First Time Buyers

app/controllers/mortgage_calculator/stamp_duties_controller.rb, app/helpers/mortgage_calculator/stamp_duties_helper.rb, app/models/mortgage_calculator/stamp_duty.rb, app/views/mortgage_calculator/stamp_duties/_bands_table.html.erb, app/views/mortgage_calculator/stamp_duties/_calculation_explanation.html.erb, app/views/mortgage_calculator/stamp_duties/_stamp_duty_tip.html.erb, config/locales/stamp_duty.cy.yml, config/locales/stamp_duty.en.yml, features/stamp_duty_information_table.feature, features/step_definitions/stamp_duty.rb, features/support/ui/pages/stamp_duty.rb, spec/helpers/stamp_duties_helper_spec.rb, spec/models/stamp_duty_spec.rb
This pr refactors the stamp duty 'how calculated' table to reduce duplication.
=> [DEV APPROVED] Refactor stamp duty info table

.gitignore, Gemfile, app/controllers/mortgage_calculator/stamp_duties_controller.rb, app/models/mortgage_calculator/stamp_duty.rb, app/views/mortgage_calculator/stamp_duties/_form_step1.html.erb, app/views/mortgage_calculator/stamp_duties/_form_step2.html.erb, app/views/mortgage_calculator/stamp_duties/_stamp_duty_to_pay_panel.html.erb, features/stamp_duty.feature, features/stamp_duty_buying_next_home.feature, features/stamp_duty_buying_second_home.feature, features/stamp_duty_first_time_buyer.feature, features/stamp_duty_information_table.feature, features/step_definitions/stamp_duty.rb, features/support/ui/pages/stamp_duty.rb, spec/models/stamp_duty_spec.rb
https://moneyadviceservice.tpondemand.com/entity/8720
This feature adds the back end functionality for new rates and standards that have been released with the latest government budget. 
First time buyer rates and thresholds have now been changed.
As all as adding this functionality, there has been quite a large refactor of the code to hopefully make it more maintainable in the future.
=> [DEV APPROVED] 8720 stamp duty calculator be feature

features/stamp_duty_information_table.feature
I am commenting this out. this is a PENDING test. however the build script does not like pending tests and decides that is a failure. therefore it is commented out. so that this can be moved to staging. 
The test is a WIP on another branch
=> [DEV APPROVED] Comment out test as pending breaks build

Dockerfile, Gemfile, Jenkinsfile, package.json, script/docker_test, script/test, spec/javascripts/karma.conf.js
https://moneyadviceservice.tpondemand.com/entity/8726
Changes required in order to add this repo in Jenkins for CI
In addition, the test group in Gemfile has been updated: to include tzinfo-data and brakeman gems.
Slight modification also required to load Angular service files in karma.conf, as I faced issues getting the Karma tests to run correctly in a Docker build.
=> Add Mortgage_calculator to Jenkins

Dockerfile, script/test
**Update Ubuntu version**
The Jenkins Docker image utilised Ubuntu 17.04, which has become end of life. This PR rolls back the version to 16.04 LTS (Long Term Support).
**Move to RVM**
Previously we were compiling ruby from source, however we have come across number of errors when older version of Ruby require additional patches to be installed. Therefore I implemented RVM (Ruby Version Manager) to manage the installation and patches.
**Security Testing**
I have also updated the test script to run Brakeman tests for informational purposes. The Jenkins job will not fail if errors and/or warnings occur, but the report will be available in the Jenkins build log.
=> Update Dockerfile & Jenkins test script for Ubuntu LTS

app/assets/javascripts/mortgage_calculator/angular/services/stamp_duty.js, app/assets/stylesheets/mortgage_calculator/components/_stamp-duty-calc.scss, app/controllers/mortgage_calculator/stamp_duties_controller.rb, app/helpers/mortgage_calculator/stamp_duties_helper.rb, app/models/mortgage_calculator/stamp_duty.rb, app/models/mortgage_calculator/tax_calculator.rb, app/views/mortgage_calculator/stamp_duties/_bands_table.html.erb, app/views/mortgage_calculator/stamp_duties/_first_time_buyer_table.html.erb, app/views/mortgage_calculator/stamp_duties/create.html.erb, app/views/mortgage_calculator/stamp_duties/show.html.erb, config/routes.rb, spec/javascripts/unit/services/stampDuty.js
[TP 8798](https://moneyadviceservice.tpondemand.com/entity/8798-create-land-and-buildings-transaction-tax)
PART 1
Refactor stamp duty calculator so adding other countires is more straight forward. Unifies the figures used to do the calculations such that Ruby and JS versions use the same banding figures.
=> 8798 create land and buildings transaction tax calculator PART 1

app/helpers/mortgage_calculator/application_helper.rb, app/views/mortgage_calculator/transaction_tax_calculator/show.html.erb, config/locales/land_and_buildings_transaction_tax.cy.yml, config/locales/land_and_buildings_transaction_tax.en.yml, config/locales/land_transaction_tax.cy.yml, config/locales/land_transaction_tax.en.yml, config/routes.rb, features/support/ui/pages/land_and_buildings_transaction_tax.rb, features/support/ui/pages/land_transaction_tax.rb, lib/mortgage_calculator/version.rb, spec/controllers/land_and_buildings_transaction_taxes_controller_spec.rb, spec/controllers/land_transaction_taxes_controller_spec.rb, spec/helpers/application_helper_spec.rb
[TP card](https://moneyadviceservice.tpondemand.com/entity/9063-seo-amends-for-land-and-buildings)
This PR addresses the following tasks:
* Add a heading description for improving the SEO value.
* Add meta tags for each calculator
* Changing links on the link to other tools section on each calculator
=> 9063 - Add SEO amends for lbbt and ltt calculators

app/helpers/mortgage_calculator/land_and_buildings_transaction_taxes_helper.rb, app/views/mortgage_calculator/land_and_buildings_transaction_taxes/_first_time_buyer_explanation.html.erb, config/locales/land_and_buildings_transaction_tax.cy.yml, config/locales/land_and_buildings_transaction_tax.en.yml, lib/mortgage_calculator/version.rb, spec/helpers/land_and_buildings_transaction_taxes_helper_spec.rb
[TP 9827](https://moneyadviceservice.tpondemand.com/restui/board.aspx#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiRkRBMzk3RTBGNjU3NDg1RDM4QzczMTJFNzI5MDFBN0MifQ==&searchPopup=userstory/9827)
Fix some errors on Welsh and how bands should display.
=> [DEV APPROVED] 9827 Minor updates to wording

app/views/mortgage_calculator/land_transaction_taxes/_calculator_form.html.erb, app/views/mortgage_calculator/land_transaction_taxes/_results_recalculation_form.html.erb, config/locales/land_transaction_tax.cy.yml, config/locales/land_transaction_tax.en.yml, features/land_transaction_tax_calculator.feature, lib/mortgage_calculator/version.rb
This PR changes the text of the land transaction calculator in accordance with the requirements of [TP11346](https://maps.tpondemand.com/restui/board.aspx?#page=userstory/11346)
=> [DEV APPROVED] change to land transaction calculator text

app/helpers/mortgage_calculator/land_and_buildings_transaction_taxes_helper.rb, app/views/mortgage_calculator/property_tax_calculator/_form_step2.html.erb, config/locales/land_and_buildings_transaction_tax.cy.yml, config/locales/land_and_buildings_transaction_tax.en.yml, config/locales/stamp_duty.cy.yml, config/locales/stamp_duty.en.yml, features/land_buildings_transaction_tax_calculator.feature, features/lbtt_how_calculated_panel.feature, features/step_definitions/land_and_buildings_transaction_tax.rb, lib/mortgage_calculator/version.rb
[TP11352](https://maps.tpondemand.com/entity/11352-ye-land-and-buildings-transaction-tax)
This work makes a number of changes to the Land and Buildings Transaction Tax Calculator to reflect Year End tax changes (see individual commits):
- Change 1: updates copy
- Change 2: updates copy and associated cucumber definitions and steps
- Change 3: updates copy
- Change 4: updates calculations and associated cucumber expectations
- Change 5: updates copy and associated cucumber expectations
- Change 6: updates copy and associated cucumber definitions
=> 11352 y/e updates lbtt calculator

config/locales/mortgage_calculator.cy.yml, config/locales/mortgage_calculator.en.yml, spec/dummy/screenshot_2020-03-19-19-07-32.565.html, spec/dummy/screenshot_2020-03-19-19-07-33.852.html, spec/dummy/screenshot_2020-03-19-19-07-33.915.html, spec/dummy/screenshot_2020-03-19-19-07-46.315.html, spec/dummy/screenshot_2020-03-19-19-07-46.466.html, spec/dummy/screenshot_2020-03-19-19-07-46.621.html, spec/dummy/screenshot_2020-03-19-19-07-46.776.html, spec/dummy/screenshot_2020-03-19-19-07-46.940.html, spec/dummy/screenshot_2020-03-19-19-07-47.095.html, spec/dummy/screenshot_2020-03-19-19-07-47.248.html, spec/dummy/screenshot_2020-03-20-12-27-10.359.html, spec/dummy/screenshot_2020-03-20-12-27-11.642.html, spec/dummy/screenshot_2020-03-20-12-27-11.696.html, spec/dummy/screenshot_2020-03-20-12-27-26.249.html, spec/dummy/screenshot_2020-03-20-16-32-14.791.html, spec/dummy/screenshot_2020-03-20-16-32-16.202.html, spec/dummy/screenshot_2020-03-20-16-32-16.249.html
[TP12274](https://maps.tpondemand.com/RestUI/Board.aspx#page=board/5175634625349962976&appConfig=eyJhY2lkIjoiOUM2MjFGQzAzOEIzQTVDNDU1NjRCMUIxQ0FENkZBOTYifQ==&boardPopup=userstory/12274/silent)
This PR did some copy changes on the MH Mortgage calculator.
=> update translation en file for mortgage calculator

config/locales/land_and_buildings_transaction_tax.cy.yml, config/locales/land_and_buildings_transaction_tax.en.yml, config/locales/land_transaction_tax.cy.yml, config/locales/land_transaction_tax.en.yml, config/locales/stamp_duty.cy.yml, config/locales/stamp_duty.en.yml
[TP12600](https://maps.tpondemand.com/restui/board.aspx#page=board/5175634625349962976&appConfig=eyJhY2lkIjoiOUM2MjFGQzAzOEIzQTVDNDU1NjRCMUIxQ0FENkZBOTYifQ==&boardPopup=userstory/12600/silent)
This PR adds target='_blank' to all external link on Stamp Duty, Land Building Transaction Calculator, and Land Transaction Tax calculators.
=> Open external link in a new tab - SD, LBTT & LTT

config/locales/affordability.cy.yml, config/locales/affordability.en.yml, spec/dummy/log/development.log
[TP12724](https://maps.tpondemand.com/restui/board.aspx?#page=board/5175634625349962976&appConfig=eyJhY2lkIjoiREI5QTI2RDFCNTJDN0JFNTQxMDRDRDIyN0ZFNDIzRDYifQ==&boardPopup=userstory/12724/silent)
This PR replace broken links in the mortgage affordability calculator
=> Replace uat partner link

config/locales/land_and_buildings_transaction_tax.cy.yml, config/locales/land_and_buildings_transaction_tax.en.yml, config/locales/land_transaction_tax.cy.yml, config/locales/land_transaction_tax.en.yml, config/locales/stamp_duty.cy.yml, config/locales/stamp_duty.en.yml
TP12728
This PR fix the broken links in the stamp duty, land and building transaction tax and land transaction tax calculator
=> 12728 broken link on result page

features/land_transaction_tax_calculator.feature, features/stamp_duty_buying_next_home.feature, features/stamp_duty_buying_second_home.feature, features/stamp_duty_information_table.feature, spec/controllers/land_transaction_taxes_controller_spec.rb, spec/helpers/land_transaction_taxes_helper_spec.rb, spec/helpers/stamp_duties_helper_spec.rb
https://maps.tpondemand.com/entity/12737-mortgage-calculator-fix-failing-tests
=> TP-12737 fix time-sensitive tests

app/models/mortgage_calculator/land_transaction_tax.rb, config/locales/land_transaction_tax.cy.yml, config/locales/land_transaction_tax.en.yml, features/land_transaction_tax_calculator.feature, lib/mortgage_calculator/version.rb, spec/controllers/land_transaction_taxes_controller_spec.rb, spec/helpers/land_transaction_taxes_helper_spec.rb, spec/models/land_transaction_tax_spec.rb
Improve the LTT tool with the latest rate changes effective 10/10.
=> Update LTT calculator for latest updates

app/controllers/mortgage_calculator/stamp_duties_controller.rb, lib/mortgage_calculator/version.rb
This has been updated for a while now so we can remove the  banner message.
=> Hide the banner for SDC

app/views/layouts/mortgage_calculator/application.html.erb
This is causing issues in production.
=> Remove bugsnag JS script
