- app/views/mortgage_calculator/affordabilities/_form_step1.html.erb
- app/views/mortgage_calculator/affordabilities/_form_step2.html.erb
- app/views/mortgage_calculator/affordabilities/_form_step3.html.erb
- app/views/mortgage_calculator/affordabilities/_header.html.erb
- app/views/mortgage_calculator/affordabilities/_next_steps_content.html.erb
- app/views/mortgage_calculator/affordabilities/next_steps.html.erb
- app/views/mortgage_calculator/repayments/_calc_left_panel.html.erb
- app/views/mortgage_calculator/repayments/_form_step1.html.erb
- app/views/mortgage_calculator/repayments/_header.html.erb
- app/views/mortgage_calculator/repayments/_next_steps_content.html.erb
Reverts moneyadviceservice/mortgage_calculator#224
Turns out the requirement was miscommunicated - we should be adding a new `h1` rather than changing the current h2.
> Revert "Use h1 for mortgage calcs"

- app/assets/javascripts/mortgage_calculator/angular/directives/integer.js
fixing firefox issue where the mortgage_term field does not allow the user to change the value with the keyboard.
> fixing firefox issue 

- app/assets/stylesheets/mortgage_calculator/components/_mortgagecalc.scss
- app/views/mortgage_calculator/affordabilities/form/_borrowing.html.erb
Fixing 2 issues:
1: The second page of the affordability calc would not display correctly due to the width of the submit button text. The right hand side of the iframe ended up hidden.
2: The borrowing slider on the third page appeared to be inactive/disabled. We discovered that it was infact enabled, however the values of the slider were upset due to the input numbers not tying in exactly with the 'step' values. We reduced the step value.
> Mortgage affordability syndication

- app/views/mortgage_calculator/affordabilities/_next_steps_content.html.erb
- app/views/mortgage_calculator/repayments/_next_steps_content.html.erb
- config/locales/affordability.cy.yml
- config/locales/affordability.en.yml
- config/locales/mortgage_calculator.cy.yml
- config/locales/mortgage_calulator.en.yml
- config/locales/stamp_duty.cy.yml
- config/locales/stamp_duty.en.yml
Welsh ones still work, but we'll remove them too for consistency.
We've also refactored the tips display in all three calculators to match the style used in the stamp duty calculator — iterating over a yaml array of tips rather than over a fixed number.
> Remove links to `news` articles, since they've been removed.

- app/assets/stylesheets/mortgage_calculator/components/_mortgagecalc.scss
- app/views/mortgage_calculator/stamp_duties/_bands_table.html.erb
- app/views/mortgage_calculator/stamp_duties/_form_step1.html.erb
- config/locales/stamp_duty.cy.yml
- config/locales/stamp_duty.en.yml
On Oct 25th, the chancellor announced higher stamp duty rates for people buying a house as a second home or to let, from April 2016. Add content to reflect that.
> Replace old stamp duty results with new legislation

- app/assets/javascripts/mortgage_calculator/angular/controllers/calculator.js
- app/views/mortgage_calculator/stamp_duties/_calc_right_panel.html.erb
- app/views/mortgage_calculator/stamp_duties/_stamp_duty_tip.html.erb
Fixes a regression issue with the Stamp Duty calculator. When clicking 'How it is calculated' the visibility of a text section needs to be toggled.
> [DEV APPROVED] 7014 - Stamp Duty text toggle link fix

- app/assets/stylesheets/mortgage_calculator/components/_expander.scss
The expander logo uses a background image. This works locally, but not on any deployed environment - Production receives a 404 error when requesting the expander.png file from the CDN, as the path was wrong.
Production (before fix):
Localhost:
> Fixing path to background image for expander

- app/assets/javascripts/mortgage_calculator/angular/controllers/calculator.js
- app/views/mortgage_calculator/repayments/_form_step2.html.erb
- app/views/mortgage_calculator/repayments/_interest_only_repayments.html.erb
- app/views/mortgage_calculator/repayments/_monthly_repayments.html.erb
- app/views/mortgage_calculator/repayments/_tabs.html.erb
- config/locales/mortgage_calculator.cy.yml
- config/locales/mortgage_calulator.en.yml
Altering tabs so they appear as tabs to the screen reader, and show you which is selected, and also how many tabs there are.  Repayment tab has attribute ``aria-selected="true"`` by default, which changes when tabs are clicked.
| Before | After |
|----------|--------|
|<img width="335" alt="screen shot 2016-02-24 at 13 05 51" src="https://cloud.githubusercontent.com/assets/13165846/13286183/717f0aaa-daf7-11e5-931c-da81b800e389.png">|<img width="326" alt="screen shot 2016-02-24 at 13 04 52" src="https://cloud.githubusercontent.com/assets/13165846/13286187/77c36870-daf7-11e5-9ce6-176a94efe708.png">|
Wrapping the monthly repayment information in a container with the properties ``aria-live="polite" aria-atomic="true"`` and including hidden text makes the updating of values easier for a screen …
> [DEV APPROVED] #7030 - Mortgage Calculator Screen Reader

- app/assets/javascripts/mortgage_calculator/angular/services/stamp_duty.js
- app/assets/stylesheets/mortgage_calculator/components/_mortgagecalc.scss
- app/assets/stylesheets/mortgage_calculator/lib/_utils.scss
- app/models/mortgage_calculator/stamp_duty.rb
- app/views/mortgage_calculator/stamp_duties/_calc_right_panel.html.erb
- app/views/mortgage_calculator/stamp_duties/_form_step1.html.erb
- app/views/mortgage_calculator/stamp_duties/_form_step2.html.erb
- config/locales/stamp_duty.cy.yml
- config/locales/stamp_duty.en.yml
- features/stamp_duty.feature
- features/step_definitions/stamp_duty.rb
- features/support/ui/pages/stamp_duty.rb
- package.json
- spec/javascripts/unit/services/stampDuty.js
- spec/models/stamp_duty_spec.rb
**Original PR (for reference):** #247
Currently the Stamp Duty Calculator only calculates for people that only own a single property. Although the copy had been updated to mention the Stamp Duty tax changes that came into force on 1st April this year, there was no way to let the tool know that you were calculating for additional properties.
This PR introduces that feature.
(The feature was added for both JavaScript and non-JavaScript pages, but the gifs for the non-JavaScript version were too large on account of the colossal amount of time it seems to take to page refresh locally 😁)
> [DEV APPROVED]Adding option to calculate for a second (or buy-to-let) home (#247)

- config/locales/stamp_duty.cy.yml
- config/locales/stamp_duty.en.yml
Adds the extra copy '£40,000 for additional homes' to the first page of the Stamp Duty Calculator.
Adds an asterisk to indicate a footnote on the second page.
> 7384 - Updating additional home copy

- lib/mortgage_calculator/version.rb
In User Story 7384 we are changing some copy in the Stamp Duty Calculator, but the PR didn't include a version bump. This corrects that.
> 7384 - Updating gem version

- app/assets/javascripts/mortgage_calculator/angular/directives/tooltip.js
- app/assets/stylesheets/mortgage_calculator/components/_affordability.scss
- app/assets/stylesheets/mortgage_calculator/components/_mortgagecalc.scss
- app/assets/stylesheets/mortgage_calculator/components/_risk.scss
- app/assets/stylesheets/mortgage_calculator/components/_tooltip.scss
- app/assets/stylesheets/mortgage_calculator/lib/_variables.scss
- app/views/mortgage_calculator/affordabilities/_field_tooltip.html.erb
- app/views/mortgage_calculator/affordabilities/_form_step3.html.erb
- app/views/mortgage_calculator/affordabilities/form/_annual_interest_rate.html.erb
- app/views/mortgage_calculator/affordabilities/form/_borrowing.html.erb
- app/views/mortgage_calculator/affordabilities/form/_term_years.html.erb
- config/locales/affordability.cy.yml
- config/locales/affordability.en.yml
This PR adds the coloured labels and tooltip with a border:
1. Changes the colours of the labels so that they are black text on a colour-changing background. This fixes a problem that we had before where the colour contrast was too low.
2. Adds a tooltip that 'persists on screen' once revealed. All of the other tooltips disappear on the 'blur' event, which is not what we want for this one as it has important content and a link within it.
3. Refactors some of the CSS for the colour-changing, and adds a class for in-page anchor links that is offset from the top (to avoid the sticky header appearing over the content).
I thought about putting the HTML for the new tooltip into a partial in the same way as the existing tooltips work - see …
> [DEV APPROVED] 7405 - New tooltip and accessibility fixes for colour changing

- app/assets/stylesheets/mortgage_calculator/components/_affordability.scss
- app/views/mortgage_calculator/affordabilities/_form_step3.html.erb
When the third step of the Mortgage Affordability Calculator loads, there is a flash of pre-formatted AngularJS template code which looks untidy.
This PR uses the `ng-cloak` directive to hide this content until AngularJS kicks in.
This is what the flash of Angular code looks like:
> 7405 - Using ng-cloak for better rendering

- app/assets/stylesheets/mortgage_calculator/components/_tooltip.scss
- app/views/mortgage_calculator/affordabilities/_form_step3.html.erb
- app/views/mortgage_calculator/affordabilities/step_3.html.erb
- config/locales/affordability.cy.yml
- config/locales/affordability.en.yml
Adds the green triangle and bold text to the link within the tooltip. Note: there is no bold text required in the Welsh version.
This also fixes a bug within `app/views/mortgage_calculator/affordabilities/step_3.html.erb` where the class was being added on the server side as well as using `ng-class`, which was resulting in duplicate classes on this element.
> 7405 Adding triangle and bold text to tooltip

- package.json
Couldn't find any clear info as to what might need changing for these to run successfully under Karma 1.x so for now locking it at 0.13.x.
Will consult @slaywell when he's back for his opinion.
> Lock karma down to v0.13.x

- app/views/mortgage_calculator/affordabilities/_form_step3.html.erb
We have a live bug with the 'Living Expenses' slider on the Mortgage Affordability Calculator. When you interact with the 'top' slider this reconfigures the 'Living Expenses' slider with unrealistically large amounts.
This is because the 'Living Expenses' slider has the same classname (`dynamic-slider-property`) with the top slider, which is creating an unwanted binding.
This PR gives the 'Living Expenses' a different classname which removes the binding between the 'Living Expenses' amount and the top slider.
The 'Living Expenses' slider is now within a range of 0-500 (if the user has not entered a value) or 20%-200% of the user entered value.
> 7350 - Dynamic sliders bug fix, correct amounts now set

- app/assets/stylesheets/mortgage_calculator/components/_stamp-duty-calc.scss
- app/assets/stylesheets/mortgage_calculator/lib/_variables.scss
- app/views/layouts/mortgage_calculator/application.html.erb
- app/views/mortgage_calculator/stamp_duties/_form_step1.html.erb
- app/views/mortgage_calculator/stamp_duties/_header.html.erb
- app/views/mortgage_calculator/stamp_duties/show.html.erb
- config/locales/stamp_duty.en.yml
This PR includes the first part of a redesign of the Stamp Duty Calculator focussing on the first page.
**Original Desktop Layout:**
**New Desktop Layout:**
**Original Mobile Layout:**
**New** Mobile Layout:
> [DEV APPROVED]Redesign first page of stamp duty calculator

- app/assets/stylesheets/mortgage_calculator/components/_stamp-duty-calc.scss
- app/views/mortgage_calculator/stamp_duties/_form_step1.html.erb
- app/views/mortgage_calculator/stamp_duties/_form_step2.html.erb
- app/views/mortgage_calculator/stamp_duties/_stamp_duty_payment.html.erb
- app/views/mortgage_calculator/stamp_duties/_stamp_duty_to_pay_panel.html.erb
This PR is to restyle the stamp duty calculator JS desktop view to bring it inline with the Optimizely (A-B tested) prototype.
The PRs related to this work are:
- [Removing Page 3 and links to it](https://github.com/moneyadviceservice/mortgage_calculator/pull/266)
- [Add items to second screen of stamp duty calculator](https://github.com/moneyadviceservice/mortgage_calculator/pull/267)
- Style Desktop JS (this PR)
- Style Tablet JS
- Style Mobile JS
- Style Non-JS Desktop
**Before**
**After**
> [DEV APPROVED] Stamp Duty Calculator: Style Desktop JS Version

- app/assets/stylesheets/mortgage_calculator/components/_stamp-duty-calc.scss
This PR is to restyle the stamp duty calculator JS tablet view to bring it inline with the Optimizely (A-B tested) prototype.
The PRs related to this work are:
- [Removing Page 3 and links to it](https://github.com/moneyadviceservice/mortgage_calculator/pull/266)
- [Add items to second screen of stamp duty calculator](https://github.com/moneyadviceservice/mortgage_calculator/pull/267)
- [Style Desktop JS](https://github.com/moneyadviceservice/mortgage_calculator/pull/268)
- Style Tablet JS (this PR)
- Style Mobile JS
- Style Non-JS Desktop
**Before**
**After**
> Stamp Duty Calculator: Style Tablet JS Version

- app/assets/stylesheets/mortgage_calculator/components/_stamp-duty-calc.scss
This PR is to restyle the stamp duty calculator JS mobile view to bring it inline with the Optimizely (A-B tested) prototype.
The PRs related to this work are:
[Removing Page 3 and links to it](https://github.com/moneyadviceservice/mortgage_calculator/pull/266)
[Add items to second screen of stamp duty calculator](https://github.com/moneyadviceservice/mortgage_calculator/pull/267)
[Style Desktop JS](https://github.com/moneyadviceservice/mortgage_calculator/pull/268)
[Style Tablet JS](https://github.com/moneyadviceservice/mortgage_calculator/pull/269)
Style Mobile JS  (this PR)
Style Non-JS Desktop
**Before**
**After**
> Stamp Duty Calculator: Style Mobile JS Version

- app/views/mortgage_calculator/stamp_duties/create.html.erb
This PR is to restyle the stamp duty calculator non JS desktop view to bring it inline with the Optimizely (A-B tested) prototype.
The PRs related to this work are:
[Removing Page 3 and links to it](https://github.com/moneyadviceservice/mortgage_calculator/pull/266)
[Add items to second screen of stamp duty calculator](https://github.com/moneyadviceservice/mortgage_calculator/pull/267)
[Style Desktop JS](https://github.com/moneyadviceservice/mortgage_calculator/pull/268)
[Style Tablet JS ](https://github.com/moneyadviceservice/mortgage_calculator/pull/269)
[Style Mobile JS](https://github.com/moneyadviceservice/mortgage_calculator/pull/270)
Style Non-JS Desktop (this PR)
**Before**
**After**
> [DEV APPROVED]Stamp Duty Calculator: Style desktop non-JS Version

- app/views/mortgage_calculator/stamp_duties/_form_step2.html.erb
This PR is to fix an pre-existing accessibility issue where the first and second pages of the stamp duty calculator forms share an id. This confuses screen readers, so we changed the id of the second form.
> [DEV APPROVED] - Adding unique id on form on second page of stamp duty calc

- app/assets/stylesheets/mortgage_calculator/components/_stamp-duty-calc.scss
- app/views/mortgage_calculator/stamp_duties/_bands_table.html.erb
- app/views/mortgage_calculator/stamp_duties/_form_step2.html.erb
- app/views/mortgage_calculator/stamp_duties/_stamp_duty_tip.html.erb
- app/views/mortgage_calculator/stamp_duties/_stamp_duty_to_pay_panel.html.erb
- config/locales/stamp_duty.cy.yml
- config/locales/stamp_duty.en.yml
Last minute changes arrived today as we were pushing through the other 6 main PRs.
Here we have:
- Pulled the 'How is this calculated?' and associated expanding explanation section into the results callout box.
- Added "Stamp Duty - Everything you need to know" link to the "Did you know?" callout section.
**Before**
**After: Unexpanded**
**After: Expanded**
> Updates to second page of stamp duty calc

- app/assets/stylesheets/mortgage_calculator/components/_stamp-duty-calc.scss
While doing QA on Firefox we noticed the focus highlight on the input was being cut off. Adding a small amount of padding to the stamp-duty__form resolves this on both pages of the Stamp Duty Calculator.
**Before:**
**After:**
> [DEV APPROVED] Resolve highlight focus issue on input

- app/assets/javascripts/mortgage_calculator/angular/directives/slider.js
When using the 'Next' button from the first page of the Stamp Duty calculator to navigate to the second page, the slider was not reconfiguring correctly to use the value from the input box.
We've refactored the functionality previously within ```input.on('blur keyup', function()``` out into ```reconfigureSlider()``` so that we can make use of it in the context of both events. 
First page - button being targeted:
Second page before - slider configured incorrectly:
Second page after - slider now correctly configured as soon as second page loads:
> [DEV APPROVED]Add configuration of slider on click of "Next" button on previous page

- app/assets/stylesheets/mortgage_calculator/components/_callout.scss
- app/assets/stylesheets/mortgage_calculator/components/_stamp-duty-calc.scss
- app/views/mortgage_calculator/affordabilities/_next_steps_content.html.erb
- app/views/mortgage_calculator/repayments/_calc_left_panel.html.erb
- app/views/mortgage_calculator/repayments/_form_step1.html.erb
- app/views/mortgage_calculator/repayments/_next_steps_content.html.erb
- app/views/mortgage_calculator/stamp_duties/_form_step2.html.erb
- lib/mortgage_calculator/version.rb
This updates the callouts on: 
- Mortgage Calculator
- Stamp Duty Calculator
- Mortgage Affordability Calculator
Also requires PR31 on Yeast - https://github.com/moneyadviceservice/yeast/pull/31 
On **Mortgage Calculator** the callouts are changed on three page views: 
**First page:** 
**Second page:** 
**Final page:** 
On **Stamp Duty Calculator** there is one change to a callout:
On **Mortgage Affordability Calculator** there is one change to a callout:
> [DEV APPROVED] TP: 7934, Comment: Updates markup and styles for mortgage tools

- lib/mortgage_calculator/version.rb
I forgot to update the version of the mortgage calculator for the PR:
https://github.com/moneyadviceservice/mortgage_calculator/pull/280
> Updating mortgage calc version with minor bump

- config/locales/stamp_duty.cy.yml
- config/locales/stamp_duty.en.yml
- lib/mortgage_calculator/version.rb
As we are approaching the 2017 - 2018 tax year we no longer need to mention that changes came into affect 'from April 2016'.
> [DEV APPROVED] 8055 - Stamp duty calculator NTY update

- app/views/mortgage_calculator/stamp_duties/_form_step1.html.erb
- lib/mortgage_calculator/version.rb
[TP Link](https://moneyadviceservice.tpondemand.com/entity/7962)
Previously the checkbox was not labeled in an accessible way. This PR uses the rails form helper to ensure the label `for` attribute is set correctly
> [DEV APPROVED] 7962 Label checkbox field correctly

- app/views/mortgage_calculator/stamp_duties/_stamp_duty_to_pay_panel.html.erb
- lib/mortgage_calculator/version.rb
[TP Link](https://moneyadviceservice.tpondemand.com/entity/7967)
The dynamic content on this page made it difficult to use with screen readers. This PR adds aria tags so stamp duty amount is announced by screen readers.
> [DEV APPROVED] 7967 Announce changes in screen readers when stamp duty value is updated

- app/views/mortgage_calculator/stamp_duties/_form_step1.html.erb
- app/views/mortgage_calculator/stamp_duties/_form_step2.html.erb
- app/views/mortgage_calculator/stamp_duties/_stamp_duty_to_pay_panel.html.erb
- app/views/mortgage_calculator/stamp_duties/show.html.erb
- lib/mortgage_calculator/version.rb
[TP Task](https://moneyadviceservice.tpondemand.com/entity/7968)
Previously the page had duplicated titles, titles with illogical structure as well as titles used for content. This PR fixes these issues so accessibility tools that rely on page titles work better.
> [DEV APPROVED] - 7968 Fix Heading structure

- app/views/mortgage_calculator/stamp_duties/_header.html.erb
- app/views/mortgage_calculator/stamp_duties/_top.html.erb
- app/views/mortgage_calculator/stamp_duties/create.html.erb
- app/views/mortgage_calculator/stamp_duties/show.html.erb
- config/locales/stamp_duty.cy.yml
- config/locales/stamp_duty.en.yml
- features/stamp_duty.feature
- features/step_definitions/stamp_duty.rb
- features/support/ui/pages/stamp_duty.rb
- lib/mortgage_calculator/version.rb
Page Titles on the Stamp Duty Calculator are not specific to the progress through the tool.
As a user relying on screen reader technology, I need the title of a page to change to inform me that I am on the results page of a tool so that I can easily tell that I have progressed.
The way Angular handles page titles makes it complicated to update the page titles within views.
This solution removes the page titles from the angular app and places them in the ruby view. These titles are not relevant to the actual angular app.
Cucumber tests were updated to represent the view changes.
During testing it was discovered that Cucumber 3.0.1 is not compatible with some of the tests being run on this tool. 
| English | Welsh |
|--------| -------|
| <img width="1163" alt="screen shot 2017-11-01 at 09 …
> [DEV APPROVED] - 7966 - Mortgage Calculator results page title

- Gemfile
- features/step_definitions/affordability.rb
- lib/mortgage_calculator/version.rb
This PR addresses an issue with existing cucumber tests within the affordability calculator. The use of a `return` in a step definition is making tests to fail in version 3.0.1 of cucumber used in the gem.
This issue is preventing deployment of work for this tool.
The use of `return` is used to skip the default values of the tests and increase the speed at which it runs. Since the use of this `return` is not essential for the running of the tests. It has been removed. The tests now pass.
> [DEV APPROVED] Cucumber test hotfix

- app/assets/stylesheets/mortgage_calculator/components/_global-alert.scss
- app/views/mortgage_calculator/stamp_duties/_budget_warning.html.erb
- app/views/mortgage_calculator/stamp_duties/show.html.erb
- config/locales/mortgage_calculator.cy.yml
- config/locales/mortgage_calulator.en.yml
- lib/mortgage_calculator/version.rb
[TP link](https://moneyadviceservice.tpondemand.com/entity/8698)
We need the standard warning message (used in beta and previous tax year end warnings) to appear at the top of the Stamp Duty Calculator. This needs to appear as the changes come into effect today
**It should read:**
Please Note:
Following the Budget announcement on 22nd November If you’re a first-time buyer:
·         you will no longer pay Stamp Duty on the first £300,000 on property purchases valued up to £500,000.
·         Between £300,000 and £500, 000 the standard rate of 5% will apply.
·         If your property purchase is over £500,000 this exemption will not apply and you will pay the standard rates of Stamp Duty.
This change applies to buyers in England, Wales and Northern Ireland.
We will be updating the tool to …
> 8698 stamp duty update

- app/assets/stylesheets/mortgage_calculator/components/_affordability.scss
- app/views/mortgage_calculator/affordabilities/_close.html.erb
- app/views/mortgage_calculator/affordabilities/_form_step1.html.erb
- app/views/mortgage_calculator/affordabilities/tooltips/_close.html.erb
- app/views/mortgage_calculator/affordabilities/tooltips/_trigger.html.erb
- config/locales/affordability.cy.yml
- config/locales/affordability.en.yml
- lib/mortgage_calculator/version.rb
[8649](https://moneyadviceservice.tpondemand.com/entity/8649) Reordering input fields 
[8651](https://moneyadviceservice.tpondemand.com/entity/8651) Wording change  
[8652](https://moneyadviceservice.tpondemand.com/entity/8652) Add tooltip (remove existing tooltips) 
Reordered input fields.
Updated copy for input labels and tooltips
Removed the on focus helper text from associated input fields.
Added an on-click, informational tooltip i  for the optional input field about "any other income".
|English| Welsh|
|-------|-------|
| ![english](https://user-images.githubusercontent.com/2187295/33080442-02378248-ced0-11e7-8364-b3f4c49b0d7b.png) | ![welsh](https://user-images.githubusercontent.com/2187295/33080454-0d0bd188-ced0-11e7-82bc-6b4065bb2397.png)|
> [DEV APPROVED]8649 Update Affordability Calculator Step 1

- app/assets/stylesheets/mortgage_calculator/base/_forms.scss
- app/assets/stylesheets/mortgage_calculator/components/_stamp-duty-calc.scss
- app/views/mortgage_calculator/stamp_duties/_form_step1.html.erb
- config/locales/stamp_duty.cy.yml
- config/locales/stamp_duty.en.yml
[TP8705](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=userstory/8711&appConfig=eyJhY2lkIjoiREREN0YzQTYyNjg0NEFCOEQxQkVFM0YwNkVDMjhFRkEifQ==&searchPopup=userstory/8705)
This PR adds a new dropdown to the initial view of the tool and removes the existing checkbox.
> TP: 8705, Comment: Adds dropdown to initial view

- app/assets/javascripts/mortgage_calculator/angular/services/stamp_duty.js
[TP8706](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=userstory/8705&appConfig=eyJhY2lkIjoiREREN0YzQTYyNjg0NEFCOEQxQkVFM0YwNkVDMjhFRkEifQ==&searchPopup=userstory/8706)
This PR adds the client-side logic for calculating Stamp Duty rates inclusive of the new rates for First Time Buyers. 
Caveat: 
This works fine in the browser I think but I am having major problems running the JS tests on this repo. These will need to be updated but that may be done as part of the final work on the feature branch, given the urgency of deploying this tool.
> TP: 8706, Comment: Updates logic for new FTB rates

- config/locales/affordability.cy.yml
- config/locales/affordability.en.yml
- lib/mortgage_calculator/version.rb
- spec/models/person_spec.rb
This PR adresses rspec testing issue introduced in https://github.com/moneyadviceservice/mortgage_calculator/pull/293
It also updates the validation messages that appear when a user leaves the step 1 questions blank.
> Updates validation messages and spec model

- app/assets/javascripts/mortgage_calculator/angular/services/stamp_duty.js
- app/assets/stylesheets/mortgage_calculator/components/_stamp-duty-calc.scss
- app/views/mortgage_calculator/stamp_duties/_bands_table.html.erb
- config/locales/stamp_duty.cy.yml
- config/locales/stamp_duty.en.yml
[TP Ticket](https://moneyadviceservice.tpondemand.com/entity/8709)
**Description**
Because Stamp Duty is calculated differently for First-time buyers, we need to change the details in the 'how is this calculated' expandable, for users who are first-time buyers.
What should happen is that first time buyers should see the content in the ticket (all of it), and 2nd home & next home buyers should see the original contents (not changed).
| First time buyers | Next home |
|--------|------|
|![image](https://user-images.githubusercontent.com/13165846/33477264-f58c5898-d67c-11e7-8392-12c908e3b975.png)|![image](https://user-images.githubusercontent.com/13165846/33477232-da8ada2e-d67c-11e7-9b33-5521af80d364.png)|
> 8709 - Updates how this is calculated section on results

- app/assets/stylesheets/mortgage_calculator/components/_stamp-duty-calc.scss
- app/views/mortgage_calculator/stamp_duties/_budget_warning.html.erb
This is a tiny PR that hides the budget warning for JS users only, this will enable us to deploy client side changes sooner (If necessary).
> [DEV APPROVED]Hide budget warning for JS users

- app/views/mortgage_calculator/stamp_duties/_bands_table.html.erb
Hot fix so the dynamic table data shows
Before
After
> [DEV APPROVED] Fix table output

- app/helpers/mortgage_calculator/stamp_duties_helper.rb
- app/views/mortgage_calculator/stamp_duties/_calculation_explanation.html.erb
- app/views/mortgage_calculator/stamp_duties/_stamp_duty_to_pay_panel.html.erb
- config/locales/stamp_duty.cy.yml
- config/locales/stamp_duty.en.yml
- spec/helpers/stamp_duties_helper_spec.rb
There is a constant already defined for the First Time Buyer threshold. This pr uses that constant in the translation files instead of the hard coded value.
> [DEV APPROVED] Replace hard coded value with variable in translation files

- config/locales/stamp_duty.cy.yml
- config/locales/stamp_duty.en.yml
- lib/mortgage_calculator/version.rb
This PR fixes an issue wth indentation in the stamp duty YAML file. 
The extra indentation was preventing the view from finding the EN and CY for:
`tooltip_show:`
`tooltip_hide:`
Fix indentation in both EN and CY YAML files.
Bump version with a patch to 2.1.1
> [DEV APPROVED] 8708 Fixes YAML indentation issue

- app/assets/javascripts/mortgage_calculator/angular/services/stamp_duty.js
- app/views/mortgage_calculator/stamp_duties/_stamp_duty_to_pay_panel.html.erb
- spec/javascripts/unit/services/stampDuty.js
[TP8736](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=userstory/8736)
This addresses a problem that has become apparent in the Stamp Duty Calculator. 
Currently the tool displays a value for the payable Stamp Duty that includes the number of pence, e.g. for a user buying their next home valued at £300,019 the result is displayed as £5,000.95. 
This PR ensures that the value is rounded down to the nearest whole pound.
> [DEV APPROVED] TP: 8736, Comment: Updates rounding in calculation

- app/views/mortgage_calculator/stamp_duties/_stamp_duty_to_pay_panel.html.erb
- spec/javascripts/unit/services/stampDuty.js
[TP8738](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=userstory/8736&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=userstory/8738)
This addresses a problem that has become apparent in the Stamp Duty Calculator. 
Currently the tool displays a value for the effective tax rate to one decimal place, e.g. for a user buying their next home valued at £300,019 the result is displayed as 1.7%. 
This PR ensures that the value is displayed to two decimal places.
> []DEV APPROVED] TP: 8738, Comment: Updates precentage display to 2 decimal places

- app/views/mortgage_calculator/stamp_duties/_stamp_duty_to_pay_panel.html.erb
- features/stamp_duty_buying_next_home.feature
- features/step_definitions/stamp_duty.rb
- features/support/ui/pages/stamp_duty.rb
[TP-8739](https://moneyadviceservice.tpondemand.com/entity/8739)
Stamp duty effective rate should be shown to 2dp
Before
After
> [DEV APPROVED] Update Stamp duty no-JS view to show effective tax rate to 2dp

- Gemfile
FactoryGirl has been replaced by FactoryBot. None of the specs in this repo use FactoryGirl so rather than upgrade to FactoryBot to address the deprecation warnings I have removed it.
> [DEV APPROVED] - Remove factory-girl-rails gem

- README.md
- app/controllers/mortgage_calculator/affordabilities_controller.rb
- app/views/mortgage_calculator/affordabilities/_default_risk_next_steps.html.erb
- app/views/mortgage_calculator/affordabilities/_high_risk_next_steps.html.erb
- app/views/mortgage_calculator/affordabilities/_low_risk_next_steps.html.erb
- app/views/mortgage_calculator/affordabilities/_medium_risk_next_steps.html.erb
- app/views/mortgage_calculator/affordabilities/_next_steps_content.html.erb
- app/views/mortgage_calculator/affordabilities/next_steps.html.erb
- config/locales/affordability.cy.yml
- config/locales/affordability.en.yml
- features/affordability.feature
- features/step_definitions/affordability.rb
- features/support/env.rb
- features/support/ui/pages/affordabiity.rb
- lib/mortgage_calculator/version.rb
- spec/controllers/affordabilities_controller_spec.rb
[8648](https://moneyadviceservice.tpondemand.com/entity/8648-update-mortgage-affordability-calculator-next-steps)
Adds different 'next steps' content to be shown depending on the risk level assigned by the tool (low, medium or high risk).
Also adds default content to be shown if someone lands directly on the 'next steps' page without having completed the tool.
> [DEV APPROVED] 8648 Update 'Next steps' content in the mortgage affordability calculator

- app/views/mortgage_calculator/affordabilities/_low_risk_next_steps.html.erb
- config/routes.rb
- lib/mortgage_calculator/version.rb
- spec/routing/affordability_routing_spec.rb
[TP 8939](https://moneyadviceservice.tpondemand.com/entity/8939-mortgage-affordability-calculator-fix-the-link)
Includes 2 small fixes for the Mortgage Affordability Calculator:
* Next steps content was updated in [8648](https://moneyadviceservice.tpondemand.com/entity/8648-update-mortgage-affordability-calculator-next-steps), however there was an error in the partial for low risk content which meant one of the links was broken. The error is corrected here.
* There's currently a broken route to post to the Welsh version of step 1 of the calculator which results in a 500 when submitting the form. The `en` route was previously updated to include `post` but it looks as though the `cy` route was missed. The `cy` route is updated here to match the `en` version.
> [DEV APPROVED] 8939: Fixes broken next steps link and broken cy route

- app/assets/stylesheets/mortgage_calculator/components/_elsewhere.scss
- app/controllers/mortgage_calculator/land_and_buildings_transaction_taxes_controller.rb
- app/helpers/mortgage_calculator/land_and_buildings_transaction_taxes_helper.rb
- app/models/mortgage_calculator/land_and_buildings_transaction_tax.rb
- app/views/mortgage_calculator/land_and_buildings_transaction_taxes/_bands_table.html.erb
- app/views/mortgage_calculator/land_and_buildings_transaction_taxes/_elsewhere.html.erb
- app/views/mortgage_calculator/land_and_buildings_transaction_taxes/_form_step1.html.erb
- app/views/mortgage_calculator/land_and_buildings_transaction_taxes/_form_step2.html.erb
- app/views/mortgage_calculator/land_and_buildings_transaction_taxes/_next_home_buyer_explanation.html.erb
- app/views/mortgage_calculator/land_and_buildings_transaction_taxes/_seo_links.html.erb
- app/views/mortgage_calculator/land_and_buildings_transaction_taxes/_stamp_duty_tip.html.erb
- app/views/mortgage_calculator/land_and_buildings_transaction_taxes/_stamp_duty_to_pay_panel.html.erb
- app/views/mortgage_calculator/land_and_buildings_transaction_taxes/create.html.erb
- app/views/mortgage_calculator/land_and_buildings_transaction_taxes/show.html.erb
- config/locales/land_and_buildings_transaction_tax.cy.yml
- config/locales/land_and_buildings_transaction_tax.en.yml
- lib/mortgage_calculator/version.rb
- spec/controllers/land_and_buildings_transaction_taxes_controller_spec.rb
- spec/models/land_and_buildings_transaction_tax_spec.rb
[TP 8798](https://moneyadviceservice.tpondemand.com/entity/8798-create-land-and-buildings-transaction-tax)
PART 2
Adds LBTT Calculator based on the changes in https://github.com/moneyadviceservice/mortgage_calculator/pull/325
The main difference between this and the stamp duty calculator is that the banding is different and there is no break for first time buyers. As such the majority of the testing is centred around the calculations being correct for given inputs as behaviourally it is identical.
> [DEV APPROVED] 8798 create land and buildings transaction tax calculator PART 2

- app/helpers/mortgage_calculator/land_and_buildings_transaction_taxes_helper.rb
- lib/mortgage_calculator/version.rb
- spec/helpers/land_and_buildings_transaction_taxes_helper_spec.rb
- spec/helpers/stamp_duties_helper_spec.rb
[TP 8798](https://moneyadviceservice.tpondemand.com/entity/8798-create-land-and-buildings-transaction-tax)
PART 3!
During PR feedback on https://github.com/moneyadviceservice/mortgage_calculator/pull/326 I introduced a bug by using the wrong calculation in the LBTT Javascript configuration when moving it to a helper from the controller. 
This also showed that I was missing a check to make sure the config was being set correctly. This PR adds a check for the config and fixes the bug.
> [DEV APPROVED] 8798 Fix error with LBTT Calculations

- app/views/mortgage_calculator/land_and_buildings_transaction_taxes/_stamp_duty_to_pay_panel.html.erb
- features/land_buildings_transaction_tax_calculator.feature
- features/step_definitions/land_and_buildings_transaction_tax.rb
- features/support/ui/pages/land_and_buildings_transaction_tax.rb
[TP Card](https://moneyadviceservice.tpondemand.com/entity/8798-land-and-buildings-transaction-tax-scotland)
The Land & Buildings Transaction Tax calculator was developed, refer to #325 and #326, The approach used to build this tool resulted in a lot ot duplicated code across c the Stamp Duty, Land & Buildings Transaction tax calculator and Land Transaction tax calculators.
This pr begins the refactoring by adding feature tests for the Land & Buildings Transaction tax calculator to facilitate the refactor.
* Since there were already cucumber steps for the stamp duty in place, the only thing to do in the feature tests is to point them to the land and buildings transaction tax instead.
* The first time buyer locale was removed from because this tool does not have the first time buyers …
> 8798 - Add feature tests for land and buildings transaction tax (Scotland)

- app/views/mortgage_calculator/land_transaction_taxes/_stamp_duty_to_pay_panel.html.erb
- features/land_transaction_tax_calculator.feature
- features/step_definitions/land_transaction_tax.rb
- features/support/ui/pages/land_transaction_tax.rb
[TP Card](https://moneyadviceservice.tpondemand.com/entity/8974-land-transaction-tax-calculator-stamp-duty)
The Land Transaction Tax calculator **for Wales** was developed already (refer to #329), The approach used to build this tool resulted in a lot of duplicated code across the Stamp Duty, Land & Buildings Transaction tax calculator and Land Transaction tax calculators.
This pr begins the refactoring by adding feature tests for the Land & Buildings Transaction tax calculator to facilitate the refactor.
* Since there were already cucumber steps for the stamp duty in place, the only thing to do in the feature tests is to point them to the land and transaction tax instead.
* The first time buyer locale was removed from because this tool does not have the first time buyers option. And this …
> Add feature tests for land transaction tax for Wales

- Gemfile
- app/controllers/mortgage_calculator/application_controller.rb
- app/controllers/mortgage_calculator/land_and_buildings_transaction_taxes_controller.rb
- app/controllers/mortgage_calculator/land_transaction_taxes_controller.rb
- app/controllers/mortgage_calculator/transaction_tax_calculator_controller.rb
- app/views/mortgage_calculator/land_and_buildings_transaction_taxes/_bands_table.html.erb
- app/views/mortgage_calculator/land_and_buildings_transaction_taxes/_form_step1.html.erb
- app/views/mortgage_calculator/land_and_buildings_transaction_taxes/_form_step2.html.erb
- app/views/mortgage_calculator/land_and_buildings_transaction_taxes/_stamp_duty_to_pay_panel.html.erb
- app/views/mortgage_calculator/land_and_buildings_transaction_taxes/show.html.erb
- app/views/mortgage_calculator/land_transaction_taxes/_bands_table.html.erb
- app/views/mortgage_calculator/land_transaction_taxes/_form_step1.html.erb
- app/views/mortgage_calculator/land_transaction_taxes/_form_step2.html.erb
- app/views/mortgage_calculator/land_transaction_taxes/_stamp_duty_to_pay_panel.html.erb
- app/views/mortgage_calculator/land_transaction_taxes/show.html.erb
- spec/controllers/land_and_buildings_transaction_taxes_controller_spec.rb
- spec/controllers/land_transaction_taxes_controller_spec.rb
[TP Card](https://moneyadviceservice.tpondemand.com/entity/8798-land-and-buildings-transaction-tax-scotland)
[TP Card](https://moneyadviceservice.tpondemand.com/entity/8974-land-transaction-tax-calculator-stamp-duty)
This is the first step of refactoring the calculators.
I create a parent class called TransactionTaxCalculator which
will be responsible for handling the objects of land and buildings and transaction tax for Scotland and land transaction tax for Wales.
Because every instance variable had it your own name  (e.g @stamp_duty, @lbtt and @ltt) and each of this names  is used on the view I created the helper method called  "resource" which will return the instance of the calculator of the page.
This will support refactoring the duplicated views later.
**Rates** now uses the name of …
> [DEV APPROVED] Refactor controllers of 8974 and 8798

- config/locales/land_transaction_tax.cy.yml
- config/locales/land_transaction_tax.en.yml
- spec/dummy/app/views/home/index.html.erb
[TP](https://moneyadviceservice.tpondemand.com/entity/8974-land-transaction-tax-calculator-stamp-duty)
Adding Welsh translations to the Land transaction tax calculator for Wales and fixing some english names for the tool.
I also added both of the tools (lbtt for Scotand and ltt for Wales) on the dummy root page so everyone that clones the repo did not need to search which url is for each calculator.
> [DEV APPROVED] 8974 add welsh translations

- config/locales/land_transaction_tax.cy.yml
- lib/mortgage_calculator/version.rb
[TP9104](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=userstory/9057&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=userstory/9104)
Corrects a wrong translation in the subtitle on the landing page of the LTT tool: 
Current: 
Updated:
> [DEV APPROVED] - TP: 9104, Comment: Corrects subtitle on calculator

- Gemfile
- app/assets/javascripts/mortgage_calculator/angular/services/stamp_duty.js
- app/helpers/mortgage_calculator/land_transaction_taxes_helper.rb
- app/models/mortgage_calculator/land_transaction_tax.rb
- app/models/mortgage_calculator/tax_calculator.rb
- features/land_transaction_tax_calculator.feature
- lib/mortgage_calculator/version.rb
[TP9255](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=userstory/9255)
The purpose of this PR is to display the Stamp Duty payable in the results section of the tool differently in the Wales version (Land Transaction Tax) than in the other versions, specifically this should be be shown to the nearest penny rather than rounded down to the nearest pound as on the other calculators. 
This calculation is made within a JavaScript scenario and non-JavaScript scenario.
> [DEV APPROVED] 9255 results rounding

- app/assets/javascripts/mortgage_calculator/angular/directives/tooltip.js
- lib/mortgage_calculator/version.rb
There was a bug where the tooltip information was constantly showing, and overlapping other tooltips.
This PR changes the hidden class to use the site wide is-hidden class on the tooltip so that the component works correctly and hides when it has the hidden class.
**Before:**
**After:**
> [DEV APPROVED] 9323 Mortgage affordability calculator tooltip bug

- app/views/mortgage_calculator/land_and_buildings_transaction_taxes/_global_alert.html.erb
- app/views/mortgage_calculator/transaction_tax_calculator/show.html.erb
- config/locales/land_and_buildings_transaction_tax.cy.yml
- config/locales/land_and_buildings_transaction_tax.en.yml
- lib/mortgage_calculator/version.rb
[TP9456](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&boardPopup=userstory/9456/silent)
This adds s holding message to the LBTT tool until we area able to make a required update to the tool.
> [DEV APPROVED] TP: 9456, Comment: Adds holding message to LBTT tool

- app/assets/javascripts/mortgage_calculator/application.js
- bower.json.erb
- lib/mortgage_calculator/engine.rb
- lib/mortgage_calculator/version.rb
- mortgage_calculator.gemspec
- spec/dummy/app/assets/javascripts/application.js
[TP10241](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=userstory/10241&appConfig=eyJhY2lkIjoiQzE1REE4NkE5M0U2Q0VFM0JCM0QyMzM2RUM0MzBGOUQifQ==)
This ticket updates the version of JQuery used in the Mortgage Calculator tool to 3.3.*
This is now ready to be merged. Note that for this tool we are keeping JQueryMigrate in place to deal with various warnings. This is subject to further future work as detailed in [TP10296](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=userstory/10296)
> [DEV APPROVED] Adds JQuery 3.3 and JQuery Migrate

- lib/mortgage_calculator/version.rb
- mortgage_calculator.gemspec
This pr is related to [TP 9827](https://moneyadviceservice.tpondemand.com/restui/board.aspx#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiRkRBMzk3RTBGNjU3NDg1RDM4QzczMTJFNzI5MDFBN0MifQ==&searchPopup=userstory/9827).
The work on this story overlapped with the jquery upgrades which necessitated locking dough-ruby to a pre upgrade version. Now that the upgrades are on production, we can change the dependency to be inline with the current version of dough-ruby.
> [DEV APPROVED] Bump dough-ruby to 3.6 for jquery upgrade

- app/helpers/mortgage_calculator/property_tax_calculator_helper.rb
- app/models/mortgage_calculator/land_and_buildings_transaction_tax.rb
- app/models/mortgage_calculator/land_transaction_tax.rb
- app/models/mortgage_calculator/stamp_duty.rb
- app/models/mortgage_calculator/tax_calculator.rb
- app/views/mortgage_calculator/property_tax_calculator/_form_step1.html.erb
- app/views/mortgage_calculator/property_tax_calculator/_next_home_buyer_explanation.html.erb
- app/views/mortgage_calculator/property_tax_calculator/show.html.erb
- config/locales/land_and_buildings_transaction_tax.cy.yml
- config/locales/land_and_buildings_transaction_tax.en.yml
- features/land_buildings_transaction_tax_calculator.feature
- features/lbtt_how_calculated_panel.feature
- features/step_definitions/stamp_duty.rb
- features/support/ui/pages/land_and_buildings_transaction_tax.rb
- lib/mortgage_calculator/version.rb
- spec/helpers/property_tax_helper_spec.rb
- spec/models/land_and_buildings_transaction_tax_spec.rb
[TP 10350](https://moneyadviceservice.tpondemand.com/restui/board.aspx#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiRkRBMzk3RTBGNjU3NDg1RDM4QzczMTJFNzI5MDFBN0MifQ==&boardPopup=userstory/10350/silent)
The Additional Dwelling Supplement for Scottish home buyers has increased from 3% to 4%. This pr makes the necessary changes to ensure the calculations are correct for Additional Property buyers in Scotland and the correct information is displayed.
> [DEV APPROVED] 10350 Additional Dwelling Supplement for Scottish home buyers

- config/locales/land_and_buildings_transaction_tax.cy.yml
- config/locales/land_and_buildings_transaction_tax.en.yml
- features/land_buildings_transaction_tax_calculator.feature
- features/land_buildings_transaction_tax_first_time_buyer.feature
- features/step_definitions/land_and_buildings_transaction_tax.rb
- features/support/ui/pages/land_and_buildings_transaction_tax.rb
- lib/mortgage_calculator/version.rb
[TP 10354](https://moneyadviceservice.tpondemand.com/restui/board.aspx#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiRkRBMzk3RTBGNjU3NDg1RDM4QzczMTJFNzI5MDFBN0MifQ==&boardPopup=userstory/10354/silent)
Specifically for the Land and Buildings Transaction Tax calculator,
the text in the call out box needs to be amended as currently it gives
incorrect information.
BEFORE
AFTER
> [DEV APPROVED] 10354 Update information text on the results page

- app/views/mortgage_calculator/affordabilities/_form_step1.html.erb
- lib/mortgage_calculator/version.rb
[TP10480](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiNTM0ODcyOThDQjBDMTMyMDgyMTBENEZEM0QwM0ZBQzkifQ==&boardPopup=bug/10480/silent)
The PopupTip Dough component is displaying wrongly on the Mortgage Affordability Calculator tool. Instead of the expected offset from the trigger element the tooltip is being rendered at a considerable distance below this. 
The reason is that the Dough component is being applied on a distant DOM element from the trigger rather than on the immediate parent. This PR moves the location of the element that loads the component to the correct place in the DOM.
> [DEV APPROVED] 10480 tooltip position

- app/assets/stylesheets/mortgage_calculator/components/_stamp-duty-calc.scss
- app/views/mortgage_calculator/land_transaction_taxes/show.html.erb
- app/views/mortgage_calculator/property_tax_calculator/show.html.erb
- config/locales/land_and_buildings_transaction_tax.cy.yml
- config/locales/land_and_buildings_transaction_tax.en.yml
- config/locales/land_transaction_tax.cy.yml
- config/locales/land_transaction_tax.en.yml
- config/locales/stamp_duty.cy.yml
- config/locales/stamp_duty.en.yml
- features/analytics.feature
- features/land_buildings_transaction_tax_calculator.feature
- features/land_transaction_tax_calculator.feature
- features/stamp_duty_buying_next_home.feature
- features/stamp_duty_buying_second_home.feature
- jenkins/test
- lib/mortgage_calculator/version.rb
[TP11736](https://maps.tpondemand.com/restui/board.aspx?#page=userstory/11736)
This work fulfils an urgent request to remove the three Stamp Duty Calculator tools and add a holding message. This is a temporary measure made necessary by the discovery of some false data on one of the tools. 
When the correct data is provided the tools should be restored to their current state (remove all the changes in this PR) and the required fix built onto that.
> [DEV APPROVED] 11736 remove tools with message

- app/assets/stylesheets/mortgage_calculator/components/_mortgagecalc.scss
- app/views/mortgage_calculator/property_tax_calculator/_bands_table.html.erb
- config/locales/land_and_buildings_transaction_tax.cy.yml
- config/locales/land_and_buildings_transaction_tax.en.yml
- features/lbtt_how_calculated_panel.feature
- lib/mortgage_calculator/version.rb
[TP11778](https://maps.tpondemand.com/entity/11778-update-to-stamp-duty-calculator-for)
This work updates the display of the table that explains how bands are calculated on the LBTT tool. This is required to add clarity to the user, particularly with regards to the higher rate of tax. 
The changes consist of 
- Updating the wording of table headings
- Updating the wording of the Additional Dwelling Supplement column
- Updating the wording of the table footer 
**Current table**
**Updated table**
> 11778 lbtt update table

- app/views/mortgage_calculator/property_tax_calculator/show.html.erb
- config/locales/land_and_buildings_transaction_tax.cy.yml
- config/locales/land_and_buildings_transaction_tax.en.yml
- config/locales/stamp_duty.cy.yml
- config/locales/stamp_duty.en.yml
- lib/mortgage_calculator/version.rb
[TP11945](https://maps.tpondemand.com/entity/11945-urgent-holding-statement-on-stamp-duty)
This work adds a holding message to the introductory text on the calculator to signal that there will be a change in Stamp Duty rates on 1 April and to provide an alternate link. 
There is a code change in the translation files for the Scotland (LBTT) version of the tool to accommodate the change made in the view, which is shared between the two calculators. This should not effect the content of the LBTT Calculator. 
**Current copy**
**Updated copy**
> Adds holding message to tool

- config/locales/mortgage_calculator.cy.yml
- config/locales/mortgage_calculator.en.yml
[TP12066](https://maps.tpondemand.com/entity/12066-update-links-on-results-page-mortgage)
This PR updates the link found in the Interest Only tab on the results page.
> 12066 - Results Page Links

- Gemfile
- features/land_transaction_tax_calculator.feature
- features/stamp_duty_buying_next_home.feature
- features/stamp_duty_buying_second_home.feature
- features/stamp_duty_first_time_buyer.feature
- features/step_definitions/stamp_duty.rb
- features/support/time_travel.rb
The current date has to be prior to the completion date so these
features were flakey unless you explicitly time-travelled to a date you
knew was prior. This change ensures this happens only where it needs to
and will automatically travel back during the teardown phase of the
feature.
These issues were realised during the development of both #381 and #382:
https://maps.tpondemand.com/entity/12600-stamp-duty-tools-sd-lbtt-and
https://maps.tpondemand.com/entity/12656-stamp-duty-tools-scotland-tool-link
> TP-12600 TP-12656 Fix time-sensitive features

- config/locales/stamp_duty.cy.yml
- config/locales/stamp_duty.en.yml
[TP12656 ](https://maps.tpondemand.com/restui/board.aspx#page=board/5175634625349962976&appConfig=eyJhY2lkIjoiOUM2MjFGQzAzOEIzQTVDNDU1NjRCMUIxQ0FENkZBOTYifQ==&boardPopup=userstory/12656/silent)
This PR remove the duplication of "and" in the bottom link on stamp duty calculator.
> Stamp Duty bottom link update

- app/views/mortgage_calculator/property_tax_calculator/show.html.erb
- config/locales/stamp_duty.cy.yml
- config/locales/stamp_duty.en.yml
- lib/mortgage_calculator/version.rb
Some customers may assume the tool has yet to be updated in line with
the latest rule changes.
> Add a banner to highlight the tool update
